### ISSUE TITLE
hi ..

### ISSUE THREAD

**Issue by shengkinng** [langyuxiansheng/biu-server-admin#5]
你好~我是后端萌星我测试遇到这问题
Debugger attached.
Debugger attached.
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json  
[nodemon] starting `node server/index.js`   
Debugger attached.
C:\Users\User\Desktop\biu-server-admin-master C:\Users\User\Desktop\biu-server-admin-master\server\src
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- C:\Users\User\Desktop\biu-server-admin-master\server\src\lib\FileUtils.js
- C:\Users\User\Desktop\biu-server-admin-master\server\src\services\common\FilesService.js
- C:\Users\User\Desktop\biu-server-admin-master\server\src\controllers\models\common\FilesController.js
- C:\Users\User\Desktop\biu-server-admin-master\server\src\controllers\models\index.js
- C:\Users\User\Desktop\biu-server-admin-master\server\src\controllers\index.js
- C:\Users\User\Desktop\biu-server-admin-master\server\src\bin\Server.js
- C:\Users\User\Desktop\biu-server-admin-master\server\index.js

**Comment by langyuxiansheng** [comment]
感谢反馈, 如果未找到 "request" 模块可以尝试安装一下"request",目前这个项目只是个雏形,biuxs的项目里的可能更完善一些,后期完善了再更新这个基础部分

**Comment by langyuxiansheng** [comment]
新版的node 貌似移除了request 模块了,需要单独安装
